niu:
  test: cow
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/helpeachother?connectTimeout=1000&useUnicode=true&characterEncoding=utf-8&useSSL=false
